[package]
name = "go-svm-examples-counter"
version = "0.1.0"
authors = ["Moshe Shababo <dicentralized@gmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
svm-sdk = { git = "https://github.com/spacemeshos/svm" }

[workspace]
